using System;
using System.Collections.Generic;
using System.Text;

namespace ARAPlus.Mod06DLL
{
    //Autogenerated
    partial class  Rechteck
    {
        public int GetUmfang()
        {
            return 2 * Laenge * Breite;
        }
    }
}
