// <auto-generated />
using System;
using ARAPlus.AspWebMitMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ARAPlus.AspWebMitMVC.Migrations
{
    [DbContext(typeof(StichprobenContext))]
    [Migration("20210301093329_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ARAPlus.AspWebMitMVC.Models.Stichprobe", b =>
                {
                    b.Property<int>("StichprobeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Abgabedatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gefahrengut")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StichprobeId");

                    b.ToTable("Stichprobe");
                });
#pragma warning restore 612, 618
        }
    }
}
